#!/bin/sh
main() {
    set -euC
    local -r JUPYTERLAB_DIR=$(jupyter lab path|sed -En 's/Application directory: *(.*)/\1/p')
    local -r PLUGIN_CONFIG="${JUPYTERLAB_DIR}/schemas/@renku/jupyterlab-vnc/plugin.json"
    local -r VNC_PATH="${JUPYTERHUB_SERVICE_PREFIX}/proxy/6080/vnc_lite.html?path=${JUPYTERHUB_SERVICE_PREFIX}/proxy/6080/"
    if [[ -e "${PLUGIN_CONFIG}" ]]; then
        sudo sed -E -i.bak 's/https:..datascience.ch/'"${VNC_PATH}"'/g' "${PLUGIN_CONFIG}"
    fi
    sudo start-stop-daemon --start --quiet --startas /usr/bin/supervisord --pidfile /var/run/supervisord.pid -- -c /etc/supervisor/supervisord.conf
}

main "$@"
